local M = {}

M.components = {
  {
    label = "ion-app",
    detail = "Ionic component",
    documentation = "Root Ionic app container.",
    insert_text = "ion-app",
  },
  {
    label = "ion-content",
    detail = "Ionic component",
    documentation = "Main scrollable content area.",
    insert_text = "ion-content",
  },
  {
    label = "ion-header",
    detail = "Ionic component",
    documentation = "Header container, usually contains ion-toolbar.",
    insert_text = "ion-header",
  },
  {
    label = "ion-footer",
    detail = "Ionic component",
    documentation = "Footer container.",
    insert_text = "ion-footer",
  },
  {
    label = "ion-toolbar",
    detail = "Ionic component",
    documentation = "Toolbar for headers and footers.",
    insert_text = "ion-toolbar",
  },
  {
    label = "ion-title",
    detail = "Ionic component",
    documentation = "Page or toolbar title.",
    insert_text = "ion-title",
  },
  {
    label = "ion-buttons",
    detail = "Ionic component",
    documentation = "Container for buttons inside a toolbar.",
    insert_text = "ion-buttons",
  },
  {
    label = "ion-button",
    detail = "Ionic component",
    documentation = "Ionic button component.",
    insert_text = "ion-button",
  },
  {
    label = "ion-icon",
    detail = "Ionic component",
    documentation = "Ionic icon component.",
    insert_text = "ion-icon",
  },
  {
    label = "ion-list",
    detail = "Ionic component",
    documentation = "List container.",
    insert_text = "ion-list",
  },
  {
    label = "ion-item",
    detail = "Ionic component",
    documentation = "List item or form row.",
    insert_text = "ion-item",
  },
  {
    label = "ion-label",
    detail = "Ionic component",
    documentation = "Label text inside items and inputs.",
    insert_text = "ion-label",
  },
  {
    label = "ion-input",
    detail = "Ionic component",
    documentation = "Text input component.",
    insert_text = "ion-input",
  },
  {
    label = "ion-textarea",
    detail = "Ionic component",
    documentation = "Textarea component.",
    insert_text = "ion-textarea",
  },
  {
    label = "ion-select",
    detail = "Ionic component",
    documentation = "Select/dropdown component.",
    insert_text = "ion-select",
  },
  {
    label = "ion-select-option",
    detail = "Ionic component",
    documentation = "Option for ion-select.",
    insert_text = "ion-select-option",
  },
  {
    label = "ion-checkbox",
    detail = "Ionic component",
    documentation = "Checkbox component.",
    insert_text = "ion-checkbox",
  },
  {
    label = "ion-radio",
    detail = "Ionic component",
    documentation = "Radio input component.",
    insert_text = "ion-radio",
  },
  {
    label = "ion-radio-group",
    detail = "Ionic component",
    documentation = "Container for ion-radio components.",
    insert_text = "ion-radio-group",
  },
  {
    label = "ion-toggle",
    detail = "Ionic component",
    documentation = "Toggle switch component.",
    insert_text = "ion-toggle",
  },
  {
    label = "ion-card",
    detail = "Ionic component",
    documentation = "Card container.",
    insert_text = "ion-card",
  },
  {
    label = "ion-card-header",
    detail = "Ionic component",
    documentation = "Card header container.",
    insert_text = "ion-card-header",
  },
  {
    label = "ion-card-title",
    detail = "Ionic component",
    documentation = "Card title.",
    insert_text = "ion-card-title",
  },
  {
    label = "ion-card-subtitle",
    detail = "Ionic component",
    documentation = "Card subtitle.",
    insert_text = "ion-card-subtitle",
  },
  {
    label = "ion-card-content",
    detail = "Ionic component",
    documentation = "Card content container.",
    insert_text = "ion-card-content",
  },
  {
    label = "ion-grid",
    detail = "Ionic component",
    documentation = "Responsive grid container.",
    insert_text = "ion-grid",
  },
  {
    label = "ion-row",
    detail = "Ionic component",
    documentation = "Grid row.",
    insert_text = "ion-row",
  },
  {
    label = "ion-col",
    detail = "Ionic component",
    documentation = "Grid column.",
    insert_text = "ion-col",
  },
  {
    label = "ion-modal",
    detail = "Ionic component",
    documentation = "Modal overlay component.",
    insert_text = "ion-modal",
  },
  {
    label = "ion-popover",
    detail = "Ionic component",
    documentation = "Popover overlay component.",
    insert_text = "ion-popover",
  },
  {
    label = "ion-alert",
    detail = "Ionic component",
    documentation = "Alert overlay component.",
    insert_text = "ion-alert",
  },
  {
    label = "ion-toast",
    detail = "Ionic component",
    documentation = "Toast notification component.",
    insert_text = "ion-toast",
  },
  {
    label = "ion-spinner",
    detail = "Ionic component",
    documentation = "Loading spinner.",
    insert_text = "ion-spinner",
  },
  {
    label = "ion-loading",
    detail = "Ionic component",
    documentation = "Loading overlay component.",
    insert_text = "ion-loading",
  },
  {
    label = "ion-refresher",
    detail = "Ionic component",
    documentation = "Pull-to-refresh container.",
    insert_text = "ion-refresher",
  },
  {
    label = "ion-refresher-content",
    detail = "Ionic component",
    documentation = "Content for ion-refresher.",
    insert_text = "ion-refresher-content",
  },
  {
    label = "ion-tabs",
    detail = "Ionic component",
    documentation = "Tabs container.",
    insert_text = "ion-tabs",
  },
  {
    label = "ion-tab-bar",
    detail = "Ionic component",
    documentation = "Tab bar container.",
    insert_text = "ion-tab-bar",
  },
  {
    label = "ion-tab-button",
    detail = "Ionic component",
    documentation = "Single tab button.",
    insert_text = "ion-tab-button",
  },
  {
    label = "ion-router-outlet",
    detail = "Ionic component",
    documentation = "Router outlet for Ionic Angular navigation.",
    insert_text = "ion-router-outlet",
  },
}

M.attributes = {
  {
    label = "color",
    detail = "Ionic attribute",
    documentation = "Sets the Ionic theme color.",
    insert_text = 'color="$1"',
  },
  {
    label = "slot",
    detail = "Ionic attribute",
    documentation = "Places the component in a named slot.",
    insert_text = 'slot="$1"',
  },
  {
    label = "fill",
    detail = "Ionic button/input attribute",
    documentation = "Visual fill style.",
    insert_text = 'fill="$1"',
  },
  {
    label = "size",
    detail = "Ionic attribute",
    documentation = "Sets component size.",
    insert_text = 'size="$1"',
  },
  {
    label = "expand",
    detail = "ion-button attribute",
    documentation = "Expands button width.",
    insert_text = 'expand="$1"',
  },
  {
    label = "shape",
    detail = "ion-button attribute",
    documentation = "Sets button shape.",
    insert_text = 'shape="$1"',
  },
  {
    label = "disabled",
    detail = "Ionic attribute",
    documentation = "Disables the component.",
    insert_text = '[disabled]="$1"',
  },
  {
    label = "routerLink",
    detail = "Angular/Ionic routing",
    documentation = "Angular router link.",
    insert_text = 'routerLink="$1"',
  },
  {
    label = "routerDirection",
    detail = "Ionic routing",
    documentation = "Controls Ionic navigation animation direction.",
    insert_text = 'routerDirection="$1"',
  },
  {
    label = "lines",
    detail = "ion-item attribute",
    documentation = "Controls item separator lines.",
    insert_text = 'lines="$1"',
  },
  {
    label = "placeholder",
    detail = "Form attribute",
    documentation = "Input placeholder.",
    insert_text = 'placeholder="$1"',
  },
  {
    label = "label",
    detail = "Form attribute",
    documentation = "Input/select label.",
    insert_text = 'label="$1"',
  },
  {
    label = "labelPlacement",
    detail = "Ionic form attribute",
    documentation = "Controls label placement.",
    insert_text = 'labelPlacement="$1"',
  },
  {
    label = "interface",
    detail = "ion-select attribute",
    documentation = "Select interface: alert, action-sheet, popover.",
    insert_text = 'interface="$1"',
  },
  {
    label = "value",
    detail = "Form attribute",
    documentation = "Sets the component value.",
    insert_text = 'value="$1"',
  },
  {
    label = "name",
    detail = "Form attribute",
    documentation = "Sets the form control name.",
    insert_text = 'name="$1"',
  },
  {
    label = "formControlName",
    detail = "Angular forms",
    documentation = "Reactive Forms control binding.",
    insert_text = 'formControlName="$1"',
  },
  {
    label = "ngModel",
    detail = "Angular forms",
    documentation = "Template-driven Forms binding.",
    insert_text = '[(ngModel)]="$1"',
  },
  {
    label = "click",
    detail = "Angular event",
    documentation = "Click event binding.",
    insert_text = '(click)="$1"',
  },
  {
    label = "ngIf",
    detail = "Angular directive",
    documentation = "Conditional rendering.",
    insert_text = '*ngIf="$1"',
  },
  {
    label = "ngFor",
    detail = "Angular directive",
    documentation = "List rendering.",
    insert_text = '*ngFor="let item of $1"',
  },
}

return M
